/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#4d4635",
        "on-surface": "#e2e2e2",
        "background": "#131313",
        "inverse-surface": "#e2e2e2",
        "surface-container": "#1f1f1f",
        "secondary-fixed-dim": "#ffb77d",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#00174b",
        "secondary-container": "#fd8b00",
        "tertiary-fixed": "#dbe1ff",
        "surface-dim": "#131313",
        "tertiary-container": "#97b0ff",
        "secondary-fixed": "#ffdcc3",
        "on-secondary-fixed-variant": "#6e3900",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#d0c5af",
        "surface": "#131313",
        "on-primary-container": "#554300",
        "on-secondary-fixed": "#2f1500",
        "inverse-primary": "#735c00",
        "on-secondary-container": "#603100",
        "primary-fixed-dim": "#e9c349",
        "on-error": "#690005",
        "surface-tint": "#e9c349",
        "on-background": "#e2e2e2",
        "surface-container-low": "#1b1b1b",
        "primary-container": "#d4af37",
        "inverse-on-surface": "#303030",
        "error-container": "#93000a",
        "on-primary": "#3c2f00",
        "on-tertiary-fixed-variant": "#27438a",
        "on-primary-fixed-variant": "#574500",
        "outline": "#99907c",
        "on-primary-fixed": "#241a00",
        "on-tertiary": "#082b72",
        "surface-bright": "#393939",
        "primary-fixed": "#ffe088",
        "surface-variant": "#353535",
        "surface-container-highest": "#353535",
        "on-tertiary-container": "#254188",
        "on-secondary": "#4d2600",
        "secondary": "#ffb77d",
        "primary": "#f2ca50",
        "tertiary": "#bfcdff",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b4c5ff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "margin-desktop": "80px",
        "gutter": "24px",
        "section-gap-mobile": "64px",
        "base": "8px",
        "margin-mobile": "20px",
        "section-gap-desktop": "120px"
      },
      "fontFamily": {
        "label-md": ["Manrope"],
        "display-lg": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Manrope"],
        "headline-lg": ["Playfair Display"],
        "body-md": ["Manrope"]
      },
      "fontSize": {
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
